### ISSUE TITLE
Multi-error return

### ISSUE THREAD

**Issue by novas0x2a** [ExaScience/pargo#2]
Re: https://github.com/ExaScience/pargo/commit/d3f88e0577949e0a5484b6198909a6630036b73b, I actually wanted to retrieve all errors, rather than just the first; to do this, I was sending the errors through the value path, so i could combine and return them.

The new error behavior doesn't prevent that, but it kind of makes the code confusing, since all my error cases are basically, `return errors.Wrap(err, "meow meow"), nil`. 

I think this is in fact a feature request for a better way to handle multi-error return; one way to handle this might be to change the pair signature to 

    // let me handle my errors the same way as my values
    pair func(x, y interface{}, xerr, yerr error) (interface{}, error),

or maybe

    // error is whatever i want it to be, the bool determines early-out
    pair func(x, y interface{}, xerr, yerr error) (interface{}, bool, error),

Thanks :)

**Comment by pcostanza** [comment]
OK, thanks a lot for opening this issue. I'm considering to create an ErrorSlice type that collects all the errors from the different tasks left-to-right in a slice, and then return that as the second error value instead. Would that help you?

**Comment by pcostanza** [comment]
Thanks a lot again for reporting this. I believe your solution, to send errors through the value path, is actually the most elegant and most flexible solution, because it leaves the choice how to deal with errors to the end user. The API also becomes a lot simpler again, which I strongly prefer.

I hope this new version works better for you.

**Comment by novas0x2a** [comment]
This looks great, sorry I missed your first message! Thanks 😀
